version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    networks:
      - network
    volumes:
      - mariadb_data:/var/lib/mysql
networks:
  network:
    driver: bridge

volumes:
    wordpress_data:
      name: wordpress_data
      driver: local
      driver_opts:
        type: none
        device: /home/sboulain/data/wordpress_data
        o: bind

    mariadb_data:
      name: mariadb_data
      driver: local
      driver_opts:
        device: /home/sboulain/data/mariadb_data
        o: bind
        type: none


