version: "3"

# volumes:
#         wordpress:
#               name: wordpress
#               driver: local
#               driver_opts:
#                     device: /goinfre/sboulain/Inception_42_sboulain/src/wordpress
#                     o: bind
#                     type: none
#         mariadb:
#               name: mariadb
#               driver: local
#               driver_opts:
#                     device: /goinfre/sboulain/Inception_42_sboulain/src/mariadb
#                     o: bind
#                     type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports:
      - "443:443"
    # depends_on:
    #   - wordpress
    # volumes:
    #   - wordpress:/var/www/html
    networks:
      - network
    # env_file:
    #   - .env
    restart: always
networks:
  network:
    driver: bridge